import localFont from "next/font/local";
import { Inter, Outfit, Roboto, Work_Sans } from "next/font/google"; 
import "./globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

const workSans = Work_Sans({
  subsets: ["latin"],
  // variable: "--font-work-sans", // You can use a custom CSS variable
  weight: "400", // Specify the weight
});

const outfit = Outfit({
  subsets: ["latin"],
  // variable: "--font-roboto", // You can use a custom CSS variable
  weight: "400", // Specify the weight
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${outfit.className} ${workSans.className} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
